version: '3.9'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: 'eingur'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'train_df'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "1234:1234"
    volumes:
      - .:/var/lib/postgresql/data
      - ../2. Init Database:/docker-entrypoint-initdb.d
