version: '3.9'

services:
  web:
    build: .
    # command: python3 /app/main.py
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  postgres:
    image: postgres:13.9-alpine
    restart: always
    environment:
      - POSTGRES_USER=eingur
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ml_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
  

